name: CI - Build Backend and Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/Koi-Center-Backend/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Create .env file
      working-directory: Koi-Center-Backend
      run: |
        echo "${{ secrets.DOTENV_FILE }}" > .env
        cat .env  # Chỉ để kiểm tra file .env được tạo, xóa lệnh này nếu không cần.

    - name: Build Backend
      working-directory: Koi-Center-Backend
      run: mvn clean package
