name: CI - Build Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.20.4

    - name: Install Dependencies
      working-directory: koi-vet-app
      run: npm ci

    - name: Fix Babel Plugin Issue
      working-directory: koi-vet-app
      run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

    - name: Build Frontend without treating warnings as errors
      working-directory: koi-vet-app
      run: CI=false npm run build
