name: CI - Build Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.20.4

    - name: Install Dependencies
      working-directory: koi-vet-app
      run: npm ci

    - name: Run ESLint (Ignore Errors)
      working-directory: koi-vet-app
      run: npm run lint || true

    - name: Build Frontend without ESLint
      working-directory: koi-vet-app
      run: SKIP_PREFLIGHT_CHECK=true npm run build
